language: android
android:
 components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-25
install:
 - nvm install 7
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH="$HOME/.yarn/bin:$PATH"
 - yarn
before_script:
 - yarn cordova prepare
 - yarn cordova compile android
script: true
jdk:
  - oraclejdk8
